package domain.user;

public enum UserType {// AQUI É UM TIPO ESPECIAL DE CLASSE USADA PARA REPRESENTAR CONJUNTO FIXO
    // DE CONSTANTES.
    COMMOM, //PESSOAS COMUNS

    MERCHANT // SÃO OS LOGISTAS
}
